@ Generated by gcc 2.6.3 for ARM/RISCiX
rfp	.req	r9
sl	.req	r10
fp	.req	r11
ip	.req	r12
sp	.req	r13
lr	.req	r14
pc	.req	r15
gcc2_compiled.:
___gnu_compiled_c:
.text
	.align	0
	.global	_tramp
_tramp:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, current_function_anonymous_args = 0
	stmfd	sp!, {lr}
	mov	ip, #1879048193
	add	ip, ip, #55836672
	add	ip, ip, #82944
	add	ip, ip, #784
	mvn	r0, #316
	sub	r0, r0, #1140850691
	sub	r0, r0, #20971520
	sub	r0, r0, #81920
	mov	lr, pc
	mov	pc, r0
	ldmfd	sp!, {pc}^
	.align	0
	.global	_jump
_jump:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, current_function_anonymous_args = 0
	mvn	r3, #316
	sub	r3, r3, #1140850691
	sub	r3, r3, #20971520
	sub	r3, r3, #81920
	mov	pc, r3	@ indirect jump
	movs	pc, lr
